/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ExperimentMetrics {
  experiment_id: string;
  fit_variant: string;
  holdout_variants: string[];
  per_variant: {
    [k: string]: {
      attention_spearman: number;
      heatmap_kl: number;
      purchase_share_mae: number;
      ad_slot_index_spearman?: number;
    };
  };
  decision_agreement: {
    kpi: string;
    winner_real: string;
    winner_synth: string;
    agree: boolean;
  };
  noise_ceiling: {
    spearman_mean: number;
    /**
     * @minItems 2
     * @maxItems 2
     */
    ci95: [number, number];
    n_splits: number;
  };
  relative_agreement?: number;
  known_effect?: {
    real_uplift?: number;
    synth_uplift?: number;
    same_direction?: boolean;
  };
  ad_to_purchase_lift?: {
    [k: string]: {
      real?: number | null;
      synth?: number;
      /**
       * @minItems 2
       * @maxItems 2
       */
      ci95?: [number, number];
    };
  };
  segment_fidelity?: {
    [k: string]: number;
  };
  n_real_accepted: number;
  n_real_rejected: number;
  n_synth: number;
  calibrated_shares?: {
    [k: string]: number;
  };
}
