/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Persona {
  persona_id: string;
  archetype: "mission" | "browser" | "loyalist" | "switcher";
  description: string;
  share_of_population: number;
}
