/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PersonaPolicy {
  persona_id: string;
  goal_categories: string[];
  time_budget_s: {
    mean: number;
    sd: number;
  };
  exploration: number;
  brand_affinity: {
    [k: string]: number;
  };
  price_sensitivity: number;
  promo_sensitivity: number;
  ad_receptivity: number;
  purchase_threshold: number;
  dwell_ms: {
    mu: number;
    sigma: number;
  };
  fixations_per_station: {
    lam: number;
  };
}
