/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Session {
  session_id: string;
  variant_id: string;
  consent: boolean;
  started_at: string;
  ended_at?: string | null;
  screen_w: number;
  screen_h: number;
  mode: "webcam" | "cursor_only";
  calibration_error_px?: number | null;
  intake?: {
    has_list: boolean;
    same_brand: boolean;
    hurry: boolean;
  };
  archetype_label?: "mission" | "browser" | "loyalist" | "switcher" | null;
  prediction_id?: string | null;
  accepted?: boolean | null;
  reject_reason?: "too_short" | "one_station" | "no_interaction" | "low_coverage" | "no_consent" | null;
  quality?: {
    fixation_coverage?: number;
    stations_visited?: number;
    duration_s?: number;
  };
}
