/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Session {
  session_id: string;
  variant_id: string;
  consent: boolean;
  started_at: string;
  /**
   * Server wall clock at the moment this session's first event was accepted. Written once, by the server, and never by a client. This is what a prediction lock's created_at is compared against in scripts/eval.py: both are stamped by the same process on the same clock, so the ordering guarantee is measured where it actually holds. Reconstructing it as started_at + t_ms instead compares a browser clock with a server one and understates every event by the POST /sessions round trip - which failed a session whose ordering was correct. Absent until an event arrives.
   */
  first_event_at?: string | null;
  ended_at?: string | null;
  screen_w: number;
  screen_h: number;
  mode: "webcam" | "cursor_only";
  calibration_error_px?: number | null;
  intake?: {
    has_list: boolean;
    same_brand: boolean;
    hurry: boolean;
  };
  archetype_label?: "mission" | "browser" | "loyalist" | "switcher" | null;
  prediction_id?: string | null;
  accepted?: boolean | null;
  reject_reason?:
    "too_few_slots" | "too_short" | "one_station" | "no_interaction" | "low_coverage" | "no_consent" | null;
  quality?: {
    fixation_coverage?: number;
    stations_visited?: number;
    slots_observed?: number;
    duration_s?: number;
  };
}
