/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SimResult {
  sim_run_id: string;
  variant_id: string;
  persona_id: string;
  n_runs: number;
  seed: number;
  fixation_prob: {
    [k: string]: number;
  };
  dwell_ms_mean: {
    [k: string]: number;
  };
  ad_slot_attention: {
    [k: string]: number;
  };
  purchase_share: {
    [k: string]: number;
  };
  ad_exposed_purchase_share?: {
    [k: string]: number;
  };
  ad_unexposed_purchase_share?: {
    [k: string]: number;
  };
  n_purchases_exposed?: number;
  n_purchases_unexposed?: number;
  path: {
    stations_mean: number;
    duration_s_mean: number;
  };
  traces?: string[];
}
