/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `Variant`'s JSON-Schema
 * via the `definition` "patch".
 */
export type Patch =
  | {
      op: "move_sku";
      sku_id: string;
      to_slot_id: string;
    }
  | {
      op: "set_ad_creative";
      ad_slot_id: string;
      creative_id: string | null;
    }
  | {
      op: "swap_texture";
      sku_id: string;
      texture_url: string;
    }
  | {
      op: "set_price";
      sku_id: string;
      price: number;
      promo?: boolean;
    };

export interface Variant {
  variant_id: string;
  base_planogram_id: string;
  name: string;
  patches: Patch[];
}
