import { Component, Suspense } from "react";
import type { ReactNode } from "react";
import { useGLTF } from "@react-three/drei";
import type { Planogram } from "@/contracts/planogram.schema";
import { aisleDisplayPlacement, type Vec3 } from "@/store/geometry";
/**
 * The one asset in this app that is not generated by `make seed` and not
 * served out of `web/public/`.
 *
 * The canonical home of third-party models is `data/models/`, next to the
 * README that records the licence, the source and the SHA-256 — the repo's own
 * layout puts data beside its provenance, and an 8.6 MB binary is not worth
 * committing twice to satisfy a bundler. `data/` is outside Vite's root
 * (`web/`), so this is a relative path rather than the `@/` alias, which only
 * maps `@/*` to `web/src/*`; `web/vite.config.ts` explains the one line of
 * config that makes it reachable in dev and in a production build.
 */
import BOTTLE_URL from "../../../data/models/WaterBottle.glb?url";

/**
 * The aisle display: a promotional plinth standing in the gap between two
 * gondolas, with the Khronos CC0 water bottle on its deck.
 *
 * Read `geometry.ts`'s aisle-display section for why it stands there and
 * nowhere else. Two things about *this* file matter just as much as the
 * placement, and both are about what an 8.6 MB decoration is not allowed to do
 * to a store that has to open instantly and stay open:
 *
 *  1. **It suspends on its own.** `PlanogramScene` keeps a "Loading shelves…"
 *     overlay over the canvas until every pack texture below its `<Suspense>`
 *     has resolved, because a click into a blank canvas is silently thrown
 *     away. Putting the model in that same boundary would hold that overlay up
 *     for the length of an 8.6 MB download — roughly tripling it — to wait for
 *     something nobody is shopping for. The boundary below is separate, so the
 *     shelves are released on the textures' schedule and the bottle arrives on
 *     its own.
 *  2. **It cannot take the store down.** `SceneErrorBoundary` in
 *     `PlanogramScene` catches texture failures and raises a full-screen
 *     message telling the reader to run `make seed`, which is right: pack
 *     textures are generated and `.gitignore`d, so a fresh clone has none.
 *     None of that applies here. This GLB *is* committed, `make seed` would do
 *     nothing for it, and a shopper does not need a bottle to shop. So this
 *     boundary is deliberately the opposite kind: it shows nothing, blocks
 *     nothing, and lets the store carry on without its decoration.
 */

/**
 * Distinct from the shelf palette (carcass `#b3b8c0`, boards `#eceef2`) so the
 * plinth never reads as another bay, but well clear of the scene background
 * `#151920` so it does not read as a shadow either: the plinth is what makes
 * the bottle a *display* rather than an object hanging in mid-air, and it can
 * only do that job if you can see it.
 */
const COLUMN_COLOR = "#49515f";
const DECK_COLOR = "#606a7c";

interface AisleDisplayBoundaryState {
  failed: boolean;
}

/**
 * The prop's own error boundary, and — like `SceneErrorBoundary` — a class,
 * because `getDerivedStateFromError` has no hook equivalent, and *inside*
 * `<Canvas>`, because `@react-three/fiber` renders through its own reconciler
 * and a boundary in the outer DOM tree cannot see an error thrown in that one.
 * Its fallback is `null` for the same reason too: a `<div>` is not a three.js
 * object, and the R3F reconciler would throw constructing one, back inside the
 * boundary that just caught.
 *
 * It reports nowhere but the console. That is the whole point, and the one
 * substantive difference from `SceneErrorBoundary`: a missing or corrupt GLB
 * should cost the shopper a bottle, not a store, so there is no `onError`
 * prop, no overlay and no message. Whoever is at a terminal still gets the
 * real error, because a decoration that vanishes without a trace is a worse
 * bug than one that fails loudly.
 */
class AisleDisplayBoundary extends Component<
  { children: ReactNode },
  AisleDisplayBoundaryState
> {
  state: AisleDisplayBoundaryState = { failed: false };

  static getDerivedStateFromError(): AisleDisplayBoundaryState {
    return { failed: true };
  }

  componentDidCatch(error: unknown): void {
    console.error(
      "AisleDisplay: the display model failed to load, so the store is " +
        "rendering without it. Nothing else is affected. Expected at " +
        "data/models/WaterBottle.glb.",
      error,
    );
  }

  render(): ReactNode {
    return this.state.failed ? null : this.props.children;
  }
}

/**
 * `useGLTF` suspends exactly like `useTexture` does — both are `suspend-react`
 * underneath — so this component is what the `<Suspense>` below is waiting on.
 *
 * `useDraco` is off: this asset carries no `extensionsUsed` at all, let alone
 * `KHR_draco_mesh_compression`, and drei's default would otherwise point a
 * DRACOLoader at a Google CDN for a file that will never need it.
 */
function DisplayBottle({ center }: { center: Vec3 }) {
  const gltf = useGLTF(BOTTLE_URL, false);

  return (
    // `name` is a real three.js `Object3D.name`: it labels the model in the
    // scene graph for anyone inspecting it, and it is what the tests look for.
    <group name="aisle-display-bottle" position={[center.x, center.y, center.z]}>
      <primitive object={gltf.scene} />
    </group>
  );
}

export interface AisleDisplayProps {
  planogram: Planogram;
}

export function AisleDisplay({ planogram }: AisleDisplayProps) {
  const place = aisleDisplayPlacement(planogram);

  return (
    <AisleDisplayBoundary>
      {/*
        No `onPointerOver`, `onPointerOut` or `onClick` anywhere below, and
        that is load-bearing rather than an omission: R3F only raycasts objects
        it has registered as interactive, and it registers an object when that
        object is given a pointer handler. A prop with none is invisible to the
        raycaster, so it can never fire a `hover` or a `pickup` event, never
        highlight, and never open a product card. Combined with `SlotMapper`
        building its screen rectangles from the planogram document alone, there
        is no path by which this bottle can be measured as a product.

        The plinth is inside the error boundary along with the model: if the
        GLB cannot load, an empty display stand left standing in the aisle is
        stranger than no display at all.
      */}
      <group name="aisle-display">
        <mesh position={[place.column.x, place.column.y, place.column.z]}>
          <boxGeometry
            args={[place.columnSize.w, place.columnSize.h, place.columnSize.d]}
          />
          <meshStandardMaterial color={COLUMN_COLOR} />
        </mesh>
        <mesh position={[place.deck.x, place.deck.y, place.deck.z]}>
          <boxGeometry args={[place.deckSize.w, place.deckSize.h, place.deckSize.d]} />
          <meshStandardMaterial color={DECK_COLOR} />
        </mesh>

        <Suspense fallback={null}>
          <DisplayBottle center={place.model} />
        </Suspense>
      </group>
    </AisleDisplayBoundary>
  );
}
