"""S1 acceptance test: seed data must validate against the generated Pydantic models.

api/app/schemas.py is generated by datamodel-code-generator from schemas/*.json
(the single cross-track contract - see CLAUDE.md). This test asserts:

  1. The seed planogram (data/planograms/demo_aisle.json) parses into the
     generated `Planogram` model.
  2. Each of variants A, B, and C (data/variants/*.json) parses into the
     generated `Variant` model.
  3. The models actually reject bad input (an unknown `source` enum value on
     the planogram, and a variant missing a required field), i.e. they are
     not just permissive pass-throughs.
"""
import copy
import json
from pathlib import Path

import pytest
from pydantic import ValidationError

from api.app.schemas import Planogram, Variant

ROOT = Path(__file__).resolve().parents[2]
PLANOGRAM_PATH = ROOT / "data" / "planograms" / "demo_aisle.json"
VARIANT_DIR = ROOT / "data" / "variants"
VARIANT_IDS = ["A", "B", "C"]


def _load(path: Path) -> dict:
    return json.loads(path.read_text())


def test_seed_planogram_parses_into_planogram_model():
    data = _load(PLANOGRAM_PATH)

    planogram = Planogram(**data)

    assert planogram.planogram_id == "demo_aisle"
    assert planogram.source.value == "manual"
    assert len(planogram.bays) == 3
    assert len(planogram.skus) == 24
    # Empty shelf positions are real slot objects (sku_id: null, facings: 0) -
    # confirm the model round-trips that, since it is load-bearing elsewhere.
    empty_slots = [
        slot
        for bay in planogram.bays
        for shelf in bay.shelves
        for slot in shelf.slots
        if slot.sku_id is None
    ]
    assert len(empty_slots) > 0
    assert all(slot.facings == 0 for slot in empty_slots)


@pytest.mark.parametrize("variant_id", VARIANT_IDS)
def test_seed_variant_parses_into_variant_model(variant_id: str):
    data = _load(VARIANT_DIR / f"{variant_id}.json")

    variant = Variant(**data)

    assert variant.variant_id == variant_id
    assert variant.base_planogram_id == "demo_aisle"


def test_planogram_rejects_unknown_source_value():
    """`source` is an enum of ["manual", "video"] with additionalProperties:
    false throughout - an unrecognised value must be rejected, not coerced."""
    data = _load(PLANOGRAM_PATH)
    bad = copy.deepcopy(data)
    bad["source"] = "telepathy"

    with pytest.raises(ValidationError):
        Planogram(**bad)


def test_variant_rejects_missing_required_field():
    """`patches` is required on Variant - dropping it must fail validation."""
    data = _load(VARIANT_DIR / "A.json")
    bad = copy.deepcopy(data)
    del bad["patches"]

    with pytest.raises(ValidationError):
        Variant(**bad)
