import { afterEach, describe, expect, it, vi } from "vitest";
import { act } from "react";
import type { ReactElement, ReactNode } from "react";
import { createRoot } from "react-dom/client";
import demoAisleJson from "../../data/planograms/demo_aisle.json";
import type { Event as ShopperEvent } from "@/contracts/event.schema";
import type { Planogram } from "@/contracts/planogram.schema";
import type { EventSink } from "@/capture/SessionSocket";
import { PlanogramScene } from "@/store/PlanogramScene";

/**
 * `.gitignore` line 15 is `web/public/textures/*.png`: pack textures are
 * generated by `make seed` (Makefile / make.bat both name the target
 * `seed`), not committed. On a fresh clone - exactly what a hackathon judge
 * does, and exactly what following the README's `make web` before
 * `make setup` does - `web/public/textures/` is empty. Every one of
 * `ProductSlot`'s 24 `useTexture` calls then 404s. `useTexture` is built on
 * `suspend-react`: it throws a pending promise while loading (handled fine by
 * `<Suspense>`), then on the retry after that promise settles, throws the
 * *real* rejection - a plain `Error`, not a thenable, so `<Suspense>` does
 * not catch it and it keeps propagating. Before this file, nothing in
 * `web/src` catches it either (grepped: no ErrorBoundary,
 * componentDidCatch or getDerivedStateFromError anywhere), so React unmounts
 * the whole tree to a blank white page - no message, no console hint, and
 * critically the HUD, cart and checkout go down with it even though none of
 * them touched a texture.
 *
 * This file proves `SceneErrorBoundary` fixes that:
 *  - a texture failure produces a message naming the real cause (generated,
 *    not committed) and the real remedy (`make seed` / `make.bat seed`, then
 *    reload) instead of a blank page;
 *  - the HUD, cart, checkout button and bay chevrons - all outside the
 *    canvas - survive the crash;
 *  - the underlying error is still logged, never swallowed;
 *  - the failure overlay replaces `sceneReadyOverlay.test.tsx`'s "Loading
 *    shelves…" overlay rather than stacking under it - `SceneReadySentinel`
 *    never mounts once the boundary has caught (its own <Suspense> subtree is
 *    exactly what got discarded), so `sceneReady` is stuck `false` forever,
 *    and a naive implementation would show "still loading" over a scene that
 *    has already permanently failed.
 */

// See sceneReadyOverlay.test.tsx for why this fake exists: the real Canvas
// needs WebGL, which jsdom does not have, and this file needs children to
// really mount so the real <Suspense>/error-boundary mechanics run.
vi.mock("@react-three/fiber", () => ({
  Canvas: ({ children }: { children?: ReactNode }) => <>{children}</>,
  useFrame: () => undefined,
  useThree: () => ({}),
}));

// Outside the boundary this file tests; faked away for the same reason as in
// sceneReadyOverlay.test.tsx.
vi.mock("@/store/StationController", () => ({
  StationController: () => null,
}));

// A controllable stand-in for the real chain (Bay -> ProductSlot ->
// `useTexture`), extended with `reject` to simulate every texture 404ing.
// `read()` throws a pending promise first, exactly like `useTexture` does
// while a fetch is in flight; `reject(error)` settles that promise and
// records a failure, so the *next* render throws `error` itself, synchronously,
// standing in for `suspend-react` re-throwing a fetch rejection. `vi.hoisted`
// is required: `vi.mock` factories run before this file's own top-level code.
const bayGate = vi.hoisted(() => {
  let state: "pending" | "ready" | "failed" = "pending";
  let pendingResolve: (() => void) | null = null;
  let failure: Error | null = null;
  return {
    read(): void {
      if (state === "ready") return;
      if (state === "failed") throw failure;
      throw new Promise<void>((resolve) => {
        pendingResolve = resolve;
      });
    },
    reject(error: Error): void {
      state = "failed";
      failure = error;
      const settle = pendingResolve;
      pendingResolve = null;
      settle?.();
    },
    reset(): void {
      state = "pending";
      pendingResolve = null;
      failure = null;
    },
  };
});

vi.mock("@/store/Bay", () => ({
  Bay: () => {
    bayGate.read();
    return null;
  },
}));

(globalThis as unknown as { IS_REACT_ACT_ENVIRONMENT: boolean }).IS_REACT_ACT_ENVIRONMENT =
  true;

const planogram = demoAisleJson as unknown as Planogram;

/** Nothing in this file interacts with a product slot, so every call is a no-op. */
class NullSink implements EventSink {
  readonly sessionId = "sess-1";
  get events(): readonly ShopperEvent[] {
    return [];
  }
  log(): void {}
  flush(): Promise<void> {
    return Promise.resolve();
  }
}

function mount(ui: ReactElement): { container: HTMLDivElement; unmount: () => void } {
  const container = document.createElement("div");
  document.body.appendChild(container);
  const root = createRoot(container);
  act(() => {
    root.render(ui);
  });
  return {
    container,
    unmount: () => {
      act(() => {
        root.unmount();
      });
      container.remove();
    },
  };
}

function mountScene(): { container: HTMLDivElement; unmount: () => void } {
  return mount(
    <PlanogramScene
      planogram={planogram}
      logger={new NullSink()}
      tracker={null}
      consent={true}
      mode="cursor_only"
    />,
  );
}

function loadingOverlay(container: HTMLElement): HTMLElement | null {
  return container.querySelector('[data-testid="scene-loading-overlay"]');
}

function errorOverlay(container: HTMLElement): HTMLElement | null {
  return container.querySelector('[data-testid="scene-error-overlay"]');
}

async function settle(): Promise<void> {
  await act(async () => {
    await Promise.resolve();
    await Promise.resolve();
    await Promise.resolve();
  });
}

/** Fails every texture in the mounted scene and lets the retry-and-throw settle. */
async function failTextures(error: Error): Promise<void> {
  await act(async () => {
    bayGate.reject(error);
  });
  await settle();
}

afterEach(() => {
  document.body.innerHTML = "";
  bayGate.reset();
});

describe("when every texture fails to load", () => {
  it("shows an actionable message instead of crashing to a blank page", async () => {
    // console.error is expected here - React itself logs every error an error
    // boundary catches, on top of whatever the boundary does with it - so it
    // is spied and silenced rather than left to spam a passing test's output.
    const consoleError = vi.spyOn(console, "error").mockImplementation(() => {});
    const view = mountScene();

    await failTextures(new Error("404: /textures/SKU_CRUNCH_1.png"));

    // The crash did not take the whole tree down: the container still holds
    // real content, not an empty shell left behind by an unhandled throw.
    expect(view.container.innerHTML).not.toBe("");

    const shown = errorOverlay(view.container);
    expect(shown).not.toBeNull();
    const text = shown?.textContent ?? "";
    // Names the real cause...
    expect(text).toContain("make seed");
    // ...and the real remedy, in both the Makefile's and make.bat's spelling -
    // guessing either would be exactly the mistake the coordinator flagged.
    expect(text).toContain("make.bat seed");
    expect(text.toLowerCase()).toContain("reload");

    view.unmount();
    consoleError.mockRestore();
  });

  it("keeps the HUD, the cart, the checkout button and the bay chevrons alive", async () => {
    const consoleError = vi.spyOn(console, "error").mockImplementation(() => {});
    const view = mountScene();

    await failTextures(new Error("404: /textures/SKU_CRUNCH_1.png"));

    expect(errorOverlay(view.container)).not.toBeNull();
    expect(view.container.textContent).toContain(planogram.name);
    expect(view.container.textContent).toContain("Cart (0)");

    const checkout = [...view.container.querySelectorAll("button")].find(
      (candidate) => candidate.textContent === "Checkout",
    );
    expect(checkout).not.toBeUndefined();
    expect(
      view.container.querySelector('button[aria-label="Previous bay"]'),
    ).not.toBeNull();
    expect(
      view.container.querySelector('button[aria-label="Next bay"]'),
    ).not.toBeNull();

    view.unmount();
    consoleError.mockRestore();
  });

  it("logs the real error instead of swallowing it", async () => {
    const consoleError = vi.spyOn(console, "error").mockImplementation(() => {});
    const view = mountScene();

    const failure = new Error("404: /textures/SKU_CRUNCH_1.png");
    await failTextures(failure);

    // Not merely "something was logged" - the boundary's own report, carrying
    // the actual error, must be among the calls. A boundary that only let
    // React's generic warning through would still be hiding what failed.
    const reportedTheRealError = consoleError.mock.calls.some((call) =>
      call.some((arg) => arg === failure || String(arg).includes(failure.message)),
    );
    expect(reportedTheRealError).toBe(true);

    // The on-screen message carries it too, for whoever is looking at the
    // store rather than a terminal.
    const shown = errorOverlay(view.container);
    expect(shown?.textContent).toContain(failure.message);

    view.unmount();
    consoleError.mockRestore();
  });

  it("replaces the loading overlay rather than stacking a permanent one under it", async () => {
    const consoleError = vi.spyOn(console, "error").mockImplementation(() => {});
    const view = mountScene();

    // Before the failure: the ordinary loading state from sceneReadyOverlay's
    // gate, not the failure overlay.
    expect(loadingOverlay(view.container)).not.toBeNull();
    expect(errorOverlay(view.container)).toBeNull();

    await failTextures(new Error("404: /textures/SKU_CRUNCH_1.png"));

    // After: SceneReadySentinel is gone for good along with the rest of the
    // crashed <Suspense> subtree, so sceneReady can never become true again.
    // The failure overlay must win outright, not share the screen with a
    // "Loading shelves…" message that is now permanently lying.
    expect(errorOverlay(view.container)).not.toBeNull();
    expect(loadingOverlay(view.container)).toBeNull();

    view.unmount();
    consoleError.mockRestore();
  });
});
